backend:
  name: git-gateway
  branch: develop # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow

media_folder: static/assets
public_folder: /assets

collections:
  - name: "clothing"
    label: "Clothing"
    folder: "src/markdown/products/clothing"
    path: "{{slug}}/{{slug}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "ID", name: "id", widget: "string", default: "{{slug}}" }
      - {
          label: "Thumbnail Image",
          name: "image",
          widget: "image",
          media_folder: "images",
        }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Description", name: "body", widget: "markdown" }
      - {
          label: "Featured",
          name: "featured",
          widget: "boolean",
          default: false,
        }
