backend:
  name: git-gateway
  branch: develop # Branch to update (optional; defaults to master)

media_folder: static/assets
public_folder: /assets


product: &PRODUCT
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Id", name: "id", widget: "string" }
      - {
          label: "Thumbnail Image",
          name: "image",
          widget: "image",
          media_folder: "images",
        }
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        field:
          {
            label: "Image",
            name: "image",
            widget: "image",
            media_folder: "images",
          }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Description", name: "body", widget: "markdown" }
      - {
          label: "Featured",
          name: "featured",
          widget: "boolean",
          default: false,
        }
      - label: "Custom Field"
        name: "customField"
        widget: "object"
        fields:
          - { label: "Field", name: "field", widget: "string" }
          - label: "Values"
            name: "values"
            widget: "list"
            fields:
              - { label: "Option", name: "option", widget: "string" }
              - { label: "Price Change", name: "priceChange", widget: "number" }



collections:
  - label: "clothing"
    name: "Clothing"
    folder: "src/markdown/products/clothing"
    path: "{{slug}}/index"
    create: true
    fields: *PRODUCT
  - label: "accessories"
    name: "Accessories"
    folder: "src/markdown/products/accessories"
    path: "{{slug}}/index"
    create: true
    fields: *PRODUCT
  - label: "home"
    name: "Home"
    folder: "src/markdown/products/home"
    path: "{{slug}}/index"
    create: true
    fields: *PRODUCT

      
