backend:
  name: git-gateway
  branch: develop # Branch to update (optional; defaults to master)
  commit_messages:
    create: CMS Create {{collection}} {{slug}}
    update: CMS Update {{collection}} “{{slug}}”
    delete: CMS Delete {{collection}} “{{slug}}”
    uploadMedia: CMS Upload “{{path}}”
    deleteMedia: CMS Delete “{{path}}”
    openAuthoring: CMS Message'{{message}}'

media_folder: static/assets
public_folder: /assets


product: &PRODUCT
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Id", name: "id", widget: "string" }
      - {
          label: "Thumbnail Image",
          name: "image",
          widget: "image",
          media_folder: "images",
        }
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        field:
          {
            label: "Image",
            name: "image",
            widget: "image",
            media_folder: "images",
          }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Description", name: "body", widget: "markdown" }
      - {
          label: "Featured",
          name: "featured",
          widget: "boolean",
          default: false,
        }
      - label: "Product Options"
        name: "productOptions"
        widget: "list"
        default: []
        fields:
              - { label: "Custom Field", name: "customField", widget: "string" }
              - label: "Options"
                name: "options"
                widget: "list"
                fields:
                  - { label: "option", name: "option", widget: "string" }
                  - { label: "Price Change", name: "priceChange", widget: "number" }



collections:
  - label: "Clothing"
    name: "clothing"
    folder: "src/markdown/products/clothing"
    path: "{{slug}}/index"
    create: true
    fields: *PRODUCT
  - label: "Accessories"
    name: "accessories"
    folder: "src/markdown/products/accessories"
    path: "{{slug}}/index"
    create: true
    fields: *PRODUCT
  - label: "Home"
    name: "home"
    folder: "src/markdown/products/home-goods"
    path: "{{slug}}/index"
    create: true
    fields: *PRODUCT
  - label: "Kids"
    name: "kids"
    folder: "src/markdown/products/kids"
    path: "{{slug}}/index"
    create: true
    fields: *PRODUCT
  - label: "Mommy and Me"
    name: "mommy-and-me"
    folder: "src/markdown/products/mommy-and-me"
    path: "{{slug}}/index"
    create: true
    fields: *PRODUCT
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "src/markdown/pages/about/index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Content, name: content, widget: markdown}
          - { label: "Image", name: "image", widget: "image", media_folder: "images",}
      - label: "Returns Page"
        name: "returns"
        file: "src/markdown/pages/returns/index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Content, name: content, widget: markdown}

      
