backend:
  name: git-gateway
  branch: develop # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow

media_folder: static/assets
public_folder: /assets

collections:
  - name: "products"
    label: "Products"
    folder: "src/markdown/products"
    path: "{{category}}/{{title}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - {
          label: "Images",
          name: "images",
          widget: "image",
          allow-multiple: true,
          media_folder: "images",
        }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Description", name: "body", widget: "markdown" }
      - {
          label: "Featured",
          name: "featured",
          widget: "boolean",
          default: false,
        }
