---
label: Product
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: text
  name: id
  label: id
- type: file
  name: image
  label: image
- type: number
  name: price
  label: price
- type: boolean
  name: featured
  label: featured
- type: field_group
  name: customField
  label: customField
  fields:
  - type: field_group_list
    name: values
    label: values
    fields:
    - type: text
      name: option
      label: option
    - type: number
      name: priceChange
      label: priceChange
  - type: text
    name: field
    label: field
